module-template: ! 'module MODULE_NAME where

'
extensions:
  GeneralizedNewtypeDeriving: true
  TemplateHaskell: true
  OverloadedStrings: true
  TypeSynonymInstances: true
  TypeFamilies: true
  MultiParamTypeClasses: true
environment: ghc-7.4.2-stable-13.09
cabal-file: project.cabal
modules:
  Handler.Hello:
    filename: src/Handler/Hello.hs
  MachineJSON:
    filename: src/MachineJSON.hs
  Handler.Aeson:
    filename: src/Handler/Aeson.hs
  Foundation:
    filename: src/Foundation.hs
  Handler.Home:
    filename: src/Handler/Home.hs
  Handler.Markdown:
    filename: src/Handler/Markdown.hs
  Import:
    filename: src/Import.hs
  Handler.Fib:
    filename: src/Handler/Fib.hs
  Main(src/Main.hs):
    filename: src/Main.hs
version: 1
extra-packages: ''
ghc-args: []
